# Generated by Django 4.1.7 on 2023-03-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdcustomer',
            name='dob',
            field=models.DateField(max_length=15),
        ),
    ]
