# Generated by Django 4.1.7 on 2023-03-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_stdcustomer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_email',
            field=models.EmailField(max_length=255),
        ),
    ]
